container:
  ports:
    - name: http
      containerPort: 11106
    - name: grpc
      containerPort: 11110

service:
  ports:
    - name: http
      port: 11106
      targetPort: http  
      protocol: TCP
    - name: grpc
      port: 11110
      targetPort: grpc  
      protocol: TCP

apiDiscovery:
  pathRouting: false 
  root: identity.shoc.dev

ingress:
  simple: true
  host: identity.shoc.dev
  service: shoc-identity 
  nginx:
    bodySize: "0"

mailing:
  enabled: false

identity:
  interactive:
    accessTokenExpiration: 300
    redirectHosts: ["http://localhost", "https://shoc.dev", "https://admin.shoc.dev", "https://identity.shoc.dev"]
    redirectPaths: ["/signed-in", "/signed-in-silent.html", "/api/auth/callback/shoc"]
    postLogoutRedirectPaths: ["/signed-out", "/"]
  m2m:
    clientId: ${SHOC_DEFAULT_M2M_CLIENT_ID}
    clientSecret: ${SHOC_DEFAULT_M2M_CLIENT_SECRET}

extraEnvs:
  - name: provider-interactive-setup-configmap
    type: configmap
    prefixed: true 
  - name: provider-setup-configmap
    type: configmap
    prefixed: true
  - name: provider-m2m-setup-secret
    type: secret
    prefixed: true