apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-provider-m2m-setup-secret"
type: Opaque
stringData:
  Identity__MachineToMachine__ClientId: {{ .Values.identity.m2m.clientId }}
  Identity__MachineToMachine__ClientSecret: {{ .Values.identity.m2m.clientSecret }}
