container:
  ports:
    - name: http
      containerPort: 11100

service:
  ports:
    - name: http
      port: 11100
      targetPort: http  
      protocol: TCP

ingress:
  template: "default"
  host: api.shoc.dev
  service: shoc-webgtw 
  nginx:
    bodySize: "0"

microservice:
  apiDiscovery:
    pathRouting: false 
    root: api.shoc.dev
  apiAuth:
    enabled: false
  apiClient:
    enabled: false
  datasource:
    enabled: false
