container:
  ports:
    - name: mysql
      containerPort: 11001

service:
  ports:
    - name: mysql
      port: 11001
      targetPort: mysql  
      protocol: TCP
  
database:
  storage: 10Gi
  storageClass: "shoc-local-storage"
  setup:
    username: ${SHOC_DATABASE_USERNAME}
    password: ${SHOC_DATABASE_PASSWORD}
    rootPassword: ${SHOC_DATABASE_ROOT_PASSWORD}
