addresses:
  root: shoc.dev
  identity: identity.shoc.dev
  api: api.shoc.dev
  admin: admin.shoc.dev

image:
  repository: imastio/shoc/public
  pullPolicy: IfNotPresent
  tag: "abc"
  pullSecretEnabled: true
  registry:
    name: ghcr.io

ingress:
  template: "none"
  clusterIssuer: shoc-cluster-issuer-prod
  port: http

service:
  template: "none"

deployment:
  template: "none"

container:
  restartPolicy: Always
  
scaling:
  replicaCount: 1