apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-setup-secret"
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.setup.rootPassword }}
  SHOC_USERNAME: {{ .Values.database.setup.username }}
  SHOC_PASSWORD: {{ .Values.database.setup.password }}

