deployment: 
  template: "microservice"

service:
  template: "default"

microservice:
  discovery:
    enabled: true
    type: static
    static:
      hostingType: docker
      defaultProtocol: http
      defaultGrpcProtocol: http
  apiDiscovery:
    enabled: true
    protocol: https
    pathRouting: true 
    root: api.shoc.dev
  apiAuth:
    enabled: true
    authority: https://identity.shoc.dev/
    allowInsecure: "false"
  apiClient:
    enabled: true
    clientId: ${SHOC_DEFAULT_M2M_CLIENT_ID}
    clientSecret: ${SHOC_DEFAULT_M2M_CLIENT_SECRET}
  mailing:
    enabled: false
    defaultProfile: default
  datasource:
    enabled: true
    server: "shoc-database"
    port: 11001
    username: ${SHOC_DATABASE_USERNAME}
    password: ${SHOC_DATABASE_PASSWORD}
    database: ${SHOC_DATABASE_NAME}
