apiDiscovery:
  enabled: true
  protocol: https
  pathRouting: true 
  root: api.shoc.dev

deployment: 
  simple: true

service:
  simple: true

container:
  restartPolicy: Always

datasource:
  enabled: true
  server: "shoc-database"
  port: 11001
  username: ${SHOC_DATABASE_USERNAME}
  password: ${SHOC_DATABASE_PASSWORD}
  database: ${SHOC_DATABASE_NAME}

apiClient:
  enabled: true
  clientId: ${SHOC_DEFAULT_M2M_CLIENT_ID}
  clientSecret: ${SHOC_DEFAULT_M2M_CLIENT_SECRET}

discovery:
  enabled: true
  type: static
  static:
    hostingType: docker
    defaultProtocol: http
    defaultGrpcProtocol: http

mailing:
  enabled: false
  defaultProfile: default

